# Generated by Django 5.2 on 2025-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_accessibility',
            field=models.CharField(choices=[('public', 'public'), ('on_invite_only', 'on_invite_only'), ('on_requests', 'on_requests')], default='public'),
        ),
    ]
